apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nn-curve-fit-ingress
  namespace: nn-curve-fit
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: nn.local   # replace with your domain or localhost mapping
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: streamlit-frontend
            port:
              number: 8501